### ISSUE TITLE
NseMqHandle这个类的作用是什么？

### ISSUE THREAD

**Issue by ZacharyJia** [lnsycmy/NseMQ#2]
感觉这个类有点迷，没有任何成员变量的话，为啥是个handle

**Comment by lnsycmy** [comment]
这个类叫`NseMqhandle`，只是因为有两个子类`NseMqProducer`和`NseMqConsumer`类都继承自它。两个子类都使用了父类的`ErrorCode`回执码，实现了`NseMqHandle`的三个功能函数。

直接叫handle确实有点奇怪，不然我再改个名吧

**Comment by ZacharyJia** [comment]
叫Handle不太合理，这种的话习惯上一般叫个XXXBase之类的
