### ISSUE TITLE
NseMqConsumerCallback里的那个成员变量好像也没有存在的必要吧

### ISSUE THREAD

**Issue by ZacharyJia** [lnsycmy/NseMQ#3]
https://github.com/lnsycmy/NseMQ/blob/8df1e4f7a3b43fd09b9bfbe94500d7c50be473e6/src/NseMqConsumerCallback.h#L25

**Comment by lnsycmy** [comment]
这个成员变量`T t_`;在`msg_package()`方法里有用到，目的是存储反序列化的数据，然后传给子类实现的函数`consume_callback(T &t)`。

**Comment by ZacharyJia** [comment]
我看除了那个函数应该也没有别的函数用到吧，那就不需要作为成员变量啊。只有一个地方用到的话，直接搞个局部变量就可以了。
